name: ecommerce_sabi
description: "Ecommerce with supabase"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^3.0.3
  cached_network_image: ^3.2.3
  intl: ^0.20.2
  go_router: ^16.3.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.0.0
  google_fonts: ^4.0.5
  image_picker: ^0.8.7
  path: ^1.8.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/products.json
    - assets/images/sb_symbol.png
    - assets/images/start_exploring_button.png
    - assets/images/sabi_putih.png
    - assets/images/login_button.png
    - assets/images/register_button.png
    - assets/images/sabi_login.png
    - assets/images/product.png
    - assets/images/sabi_catalog.png
    - assets/images/buy_now.png
    - assets/images/login_buy_now.png
    - assets/images/add_to_bag.png
    - assets/images/alex.jpg
    - assets/images/sabi_checkout.png
    - assets/images/save_button.png
    - assets/images/add_new_product_button.png
    - assets/images/place_order_button.png
